library

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn import svm

2.load data set

In [2]:
prediksi_cuaca_dataset = pd.read_csv('prediksi_cuaca.csv')
prediksi_cuaca_dataset.drop('weather', axis=1, inplace=True)

In [3]:
prediksi_cuaca_dataset.head()

precipitation  temp_max  temp_min  wind  output
0            0.0      12.8       5.0   4.7       1
1           10.9      10.6       2.8   4.5       2
2            0.8      11.7       7.2   2.3       2
3           20.3      12.2       5.6   4.7       2
4            1.3       8.9       2.8   6.1       2

In [4]:
prediksi_cuaca_dataset.shape

(1461, 5)

In [5]:
prediksi_cuaca_dataset['output'].value_counts() 

output
2    641
0    640
4    101
1     53
3     26
Name: count, dtype: int64

In [6]:
prediksi_cuaca_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   precipitation  1461 non-null   float64
 1   temp_max       1461 non-null   float64
 2   temp_min       1461 non-null   float64
 3   wind           1461 non-null   float64
 4   output         1461 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 57.2 KB


In [7]:
prediksi_cuaca_dataset.describe()

precipitation     temp_max     temp_min         wind       output
count    1461.000000  1461.000000  1461.000000  1461.000000  1461.000000
mean        3.029432    16.439083     8.234771     3.241136     1.243669
std         6.680194     7.349758     5.023004     1.437825     1.229560
min         0.000000    -1.600000    -7.100000     0.400000     0.000000
25%         0.000000    10.600000     4.400000     2.200000     0.000000
50%         0.000000    15.600000     8.300000     3.000000     2.000000
75%         2.800000    22.200000    12.200000     4.000000     2.000000
max        55.900000    35.600000    18.300000     9.500000     4.000000

In [8]:
prediksi_cuaca_dataset[prediksi_cuaca_dataset['temp_min']==min(prediksi_cuaca_dataset['temp_min'])]

precipitation  temp_max  temp_min  wind  output
706            0.0       0.0      -7.1   3.1       0

In [9]:
prediksi_cuaca_dataset[prediksi_cuaca_dataset['temp_max']==max(prediksi_cuaca_dataset.temp_max)]

precipitation  temp_max  temp_min  wind  output
953            0.5      35.6      17.8   2.6       2

In [10]:
X = prediksi_cuaca_dataset.drop(columns='output', axis=1)
Y = prediksi_cuaca_dataset['output'] 

In [11]:
print (X)

      precipitation  temp_max  temp_min  wind
0               0.0      12.8       5.0   4.7
1              10.9      10.6       2.8   4.5
2               0.8      11.7       7.2   2.3
3              20.3      12.2       5.6   4.7
4               1.3       8.9       2.8   6.1
...             ...       ...       ...   ...
1456            8.6       4.4       1.7   2.9
1457            1.5       5.0       1.7   1.3
1458            0.0       7.2       0.6   2.6
1459            0.0       5.6      -1.0   3.4
1460            0.0       5.6      -2.1   3.5

[1461 rows x 4 columns]


In [12]:
print (Y)

0       1
1       2
2       2
3       2
4       2
       ..
1456    2
1457    2
1458    4
1459    0
1460    0
Name: output, Length: 1461, dtype: int64


Standarisasi data

In [13]:
scaler = StandardScaler()

In [14]:
scaler.fit(X)

StandardScaler()

In [15]:
standarized_data = scaler.transform(X) 

In [16]:
print(standarized_data)

[[-0.45364986 -0.49529914 -0.64421175  1.01497975]
 [ 1.17859791 -0.79473121 -1.08234662  0.87583314]
 [-0.33385186 -0.64501518 -0.20607688 -0.65477956]
 ...
 [-0.45364986 -1.25748987 -1.52048149 -0.44605965]
 [-0.45364986 -1.47525865 -1.83912504  0.11052679]
 [-0.45364986 -1.47525865 -2.05819247  0.18010009]]


In [17]:
X = standarized_data
Y = prediksi_cuaca_dataset['output'] 

In [18]:
print(X)
print(Y)

[[-0.45364986 -0.49529914 -0.64421175  1.01497975]
 [ 1.17859791 -0.79473121 -1.08234662  0.87583314]
 [-0.33385186 -0.64501518 -0.20607688 -0.65477956]
 ...
 [-0.45364986 -1.25748987 -1.52048149 -0.44605965]
 [-0.45364986 -1.47525865 -1.83912504  0.11052679]
 [-0.45364986 -1.47525865 -2.05819247  0.18010009]]
0       1
1       2
2       2
3       2
4       2
       ..
1456    2
1457    2
1458    4
1459    0
1460    0
Name: output, Length: 1461, dtype: int64


In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, stratify=Y, random_state=2)

In [20]:
print(X.shape, X_train.shape, X_test.shape)

(1461, 4) (1168, 4) (293, 4)


In [21]:
classifier = LogisticRegression()

In [22]:
classifier.fit(X_train, Y_train)

LogisticRegression()

In [23]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [24]:
print('Akurasi data training adalah =', training_data_accuracy)

Akurasi data training adalah = 0.791095890410959


In [25]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [26]:
print('Akurasi data testing adalah =', test_data_accuracy)

Akurasi data testing adalah = 0.7747440273037542


model prediksi

In [27]:
import numpy as np
# Data input
input_data = (2.5, 1.7, -2.8, 5)

# Memuat model yang telah dilatih
from sklearn.linear_model import LogisticRegression  # Misalkan classifier menggunakan LogisticRegression

# Memuat scaler yang telah difit
from sklearn.preprocessing import StandardScaler

# Ubah input_data menjadi array numpy
input_data_as_numpy_array = np.array(input_data)

# Ubah bentuk array menjadi (1, -1)
input_data_reshape = input_data_as_numpy_array.reshape(1, -1)

# Standarisasi data
std_data = scaler.transform(input_data_reshape)

# Lakukan prediksi
prediction = classifier.predict(std_data)

# Interpretasi hasil prediksi
if prediction[0] == 0:
    print('Aman untuk keluar')
elif prediction[0] == 1:
    print('Aman untuk keluar')
elif prediction[0] != 2:
    print('Tidak aman untuk keluar')
elif prediction[0] != 3:
    print('Tidak aman untuk keluar')
else:
    print('Terjadi kesalahan pada model. Silakan periksa kembali model Anda.')

Tidak aman untuk keluar


c:\Users\fadhel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [28]:
import pickle

In [29]:
filename = 'prediksi_cuaca.sav'
pickle.dump(classifier, open(filename, 'wb'))